apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: thoaitrands/aws-backend:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysql:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
        - name: spring.datasource.username
          value: root
        - name: spring.datasource.password
          value: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
