apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: demo-app-mysql    # The name of mysql service
  mysql-database-name: testdb     # The name of the database used by the demo app
